exec-once = hypridle & mako & waybar & fcitx5
exec-once = swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-clip-persist --clipboard regular & clipse -listen
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] zen-browser
exec-once = [workspace 3 silent] thunderbird
exec-once = [workspace 4 silent] nautilus
exec-once = [workspace 5 silent] chromium --new-window --ozone-platform=wayland --app="https://chatgpt.com"
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
